import { NextResponse } from "next/server";

const hints: string[] = [
  "🤖 Wanna chat with me?",
  "👉 Click me, I don’t bite!",
  "💡 I might just surprise you...",
  "⚡ Boost your brainpower, try me!",
  "🕹️ Press the button, let’s play!",
  "🎯 Got a question? I’ve got answers!",
  "🔥 Click me before I disappear...",
  "🎉 I’m fun, I promise!",
  "🚀 Let’s take off together!",
  "🧠 Feed me your thoughts!",
  "👀 I see you... click me!",
  "💬 Let’s talk, human!",
  "🤔 Curious? Press here!",
  "🎵 I’m better than elevator music!",
  "🌟 The magic starts here!",
  "🔮 Ask me anything, I’m ready!",
  "😎 You know you wanna click...",
  "🍿 Let’s make this interesting!",
  "💌 Your personal AI awaits!",
  "🛸 Beam me up with a click!",
  "📚 I know a thing or two...",
  "🕵️ I’ve got secrets to share...",
  "🎭 Click me for a show!",
  "🌍 Explore the unknown with me!",
  "🧩 Let’s solve puzzles together!",
  "⏳ Don’t wait, I’m here now!",
  "⚙️ I’ve got features you’ll love!",
  "🎮 Bonus level unlocked → Click!",
  "📡 I’m tuned into you!",
  "💎 Rare AI gem inside!",
  "✨ Click for instant magic!",
  "🎤 Mic check... ready to talk?",
  "🥇 You’re #1 if you click me!",
  "💡 I might spark an idea!",
  "🤯 Prepare to be amazed!",
  "📖 Let’s write a story together!",
  "🍀 Lucky button right here!",
  "🎨 Let’s create something cool!",
  "🔓 Unlock fun with a click!",
  "🎶 I sing in binary, wanna hear?",
  "🚦 Green means go → Click me!",
  "🏆 Champion move: press me!",
  "🎲 Roll the dice, see what happens!",
  "📸 Say cheese... just kidding, click!",
  "🤝 Let’s team up!",
  "👾 I come in peace... mostly!",
  "⚡ Instant dopamine, guaranteed!",
  "🛠️ I’ve got tools for you!",
  "🥳 I’m more fun than TikTok!",
  "🧃 Freshly squeezed hints, just for you!",
  "🎯 Your destiny: click here!",
  "🍕 Extra cheese if you click me!",
  "📺 Better than Netflix, promise!",
  "🥤 Sip, click, repeat!",
  "🎧 Press play on me!",
  "🛹 Let’s roll!",
  "🍎 An apple a day keeps boredom away!",
  "📦 Surprise inside this button!",
  "🐱 Purrfect click awaits!",
  "🐶 Loyal button waiting for you!",
  "🐒 Monkey see, monkey click!",
  "🦊 Clever humans click here!",
  "🐉 Dragons fear this button!",
  "🦄 Magical things await!",
  "🛡️ Protect your fun → click!",
  "⚔️ Ready for adventure?",
  "🏹 Bullseye: hit this button!",
  "🗺️ Your journey starts here!",
  "🌋 Explosive fun inbound!",
  "❄️ Coolest button on the site!",
  "🔥 Spicy surprise if you click!",
  "🍫 Sweet reward inside!",
  "🍭 Candy-coated fun!",
  "🍩 Hole-y fun here!",
  "🥨 Twist of fate → click me!",
  "🧁 Frosted fun ahead!",
  "🍦 Scoop of joy if you press!",
  "🍪 Cookies approve this click!",
  "☕ Coffee says: click me!",
  "🍹 Tropical vibes inside!",
  "🍔 Extra pickles included!",
  "🍟 Fries with that click?",
  "🌮 Taco Tuesday awaits!",
  "🍣 Sushi roll of wisdom!",
  "🥗 Fresh ideas inside!",
  "🥩 Juicy content right here!",
  "🥑 Guac is extra, click is free!",
  "🍄 Mushroom boost inbound!",
  "🧄 Garlic-approved fun!",
  "🥕 Carrot click therapy!",
  "🌽 Corny joke: click me!",
  "🍍 Pineapple power engaged!",
  "🍇 Grapes of wisdom here!",
  "🍓 Berry good idea!",
  "🍉 Slice of fun awaits!",
  "🍒 Cherry on top!",
  "🍌 Go bananas with me!",
  "🥝 Kiwi surprise inside!",
  "🥥 Coconut vibes unlocked!",
  "🍋 Squeeze me for fun!",
  "🍊 Orange you gonna click?",
  "🍏 Green apple delight!",
  "🥭 Mango madness inside!",
  "🍐 Pear-fect click awaits!",
  "🍈 Melon-tastic idea!",
  "🍑 Peachy fun right here!",
  "🍷 Sip of wisdom here!",
  "🥂 Cheers to a click!",
  "🍺 Cold one with this button!",
  "🍻 Best buds click together!",
  "🥃 Strong content ahead!",
  "🍶 Sake surprise inside!",
  "🍸 Fancy fun awaits!",
  "🍹 Party mode engaged!",
  "🍼 Baby’s first click?",
  "🥛 Got milk? Got click!",
  "💧 Hydrate with this click!",
  "🌌 Stars align for your click!",
  "🌙 Moon says hello!",
  "☀️ Sunshine in a click!",
  "⚡ Thunderstruck button!",
  "🌊 Surf’s up, click now!",
  "🏔️ Peak fun achieved!",
  "🏝️ Island vibes here!",
  "🏜️ Desert adventure inside!",
  "🌋 Lava-hot click!",
  "🏕️ Campfire stories start here!",
  "🌳 Root of all fun!",
  "🌵 Sharp idea → click me!",
  "🍂 Fall into fun!",
  "❄️ Snowball of joy!",
  "🌸 Blossom your day!",
  "🌼 Bloom with me!",
  "🌻 Sunflower vibes!",
  "🌺 Tropical paradise here!",
  "🌹 Classic fun inside!",
  "🌷 Spring vibes unlocked!",
  "🌐 Explore me!",
  "🛰️ Orbiting good vibes!",
  "🪐 Planet of wisdom!",
  "☄️ Shooting star of fun!",
  "🛸 UFO-powered hints!",
  "🚀 Blast off inside!",
  "👩‍🚀 Space adventures await!",
  "🖥️ Code hidden here!",
  "📱 I fit in your pocket!",
  "⌨️ Type faster, click harder!",
  "🖱️ One click away!",
  "💾 Save fun → click me!",
  "🖨️ Printing fun inside!",
  "💻 Hack the fun here!",
  "🕹️ Classic gamer mode!",
  "🎮 New game unlocked!",
  "🎲 Critical hit chance!",
  "♟️ Chess move: click!",
  "🃏 Wild card inside!",
  "🎰 Jackpot if you press!",
  "🎯 Dartboard hit → click!",
  "🏀 Slam dunk here!",
  "⚽ Goal → click me!",
  "⚾ Home run button!",
  "🎳 Strike of fun!",
  "🎾 Ace your click!",
  "🥊 Knockout punch here!",
  "🥋 Ninja-approved!",
  "🏓 Ping pong vibes!",
  "🏸 Smash this click!",
  "🏒 Ice cold fun!",
  "🎿 Ski into joy!",
  "🏂 Shred the boredom!",
  "🚴 Pedal into excitement!",
  "🏍️ Ride into fun!",
  "🚗 Vroom! Click here!",
  "🚕 Taxi to good vibes!",
  "🚙 Road trip button!",
  "🚌 All aboard fun express!",
  "🚓 Police say click it!",
  "🚑 Emergency fun!",
  "🚒 Firetruck of joy!",
  "🚜 Tractor beam of fun!",
  "🚛 Big rig click!",
  "🚚 Delivery of fun!",
  "🚀 Space delivery inbound!",
  "🛶 Paddle to adventure!",
  "⛵ Sail away with me!",
  "🚤 Speedboat vibes!",
  "🛳️ Cruise into fun!",
  "✈️ Flight to good times!",
  "🪂 Skydiving into fun!",
  "🚁 Helicopter fun drop!",
  "⚡ Power-up inside!",
  "🔋 Fully charged fun!",
  "🔑 Unlock joy here!",
  "💡 Bright idea button!",
  "📣 Shout-out → click me!",
  "📞 Ring ring… it’s fun!",
  "✉️ Message unlocked here!",
  "📬 Special delivery: fun!",
  "📦 Surprise in a box!",
  "🎁 Gift wrapped for you!",
  "🎉 Party starts with a click!",
  "🎂 Sweet treat button!",
  "🍬 Candy vibes inside!",
  "🍿 Popcorn wisdom here!",
  "🎈 Balloon of joy!",
  "🎀 Bow-tied fun!",
  "🛒 Add fun to cart!",
  "🏷️ Discount: 100% free fun!",
  "🧾 Receipt of joy!",
  "💰 Jackpot vibes!",
  "💎 Diamond button here!",
  "🔔 Ding ding → fun awaits!",
  "⏰ Time to click me!",
  "📅 Best day to click!",
  "📍 You’re here → click!",
  "🧭 Compass points here!",
  "🗿 Ancient wisdom inside!",
  "📀 Golden click inside!",
  "⚖️ Balanced fun ahead!",
  "🧱 Building blocks of joy!",
  "🔨 Hammer your boredom!",
  "⛏️ Mine some fun!",
  "🪓 Chop into fun!",
  "🔧 Tune into joy!",
  "🧰 Toolbox of fun!",
  "🔩 Screw it, just click!",
  "🔩 Nuts & bolts of joy!",
  "⚙️ Gears turning for fun!",
  "🧪 Potion of joy brewed!",
  "🧬 DNA of fun inside!",
  "💉 Injecting joy here!",
  "🩺 Doctor says: click!",
  "🧼 Fresh clean fun!",
  "🛁 Bubble bath vibes!",
  "🚿 Shower of fun!",
  "🧴 Lotion of joy!",
  "💄 Glam up your click!",
  "💅 Nail polish of fun!",
  "👠 Fancy step → click!",
  "👑 Crown yourself with joy!",
  "💍 Ring of fun awaits!",
  "🕶️ Cool vibes inside!",
  "👓 See clearly → click!",
  "🎩 Hat tip to fun!",
  "🧢 Cap off boredom!",
  "👕 Fresh fit unlocked!",
  "👟 Step into fun!",
  "🥾 Adventure boots on!",
  "🧤 Gloves off → click!",
  "🧣 Cozy click awaits!",
  "🧥 Jacket of joy!",
  "👔 Tie it up with fun!",
  "🩳 Shorts weather click!",
  "👙 Summer fun button!",
  "🩱 Poolside vibes here!",
  "🩲 Silly shorts mode!",
  "👗 Dress up your click!",
  "🧦 Sock surprise here!",
  "🥽 Goggles of joy!",
  "🎒 Backpack full of fun!",
  "👛 Purse of happiness!",
  "👜 Bag of joy here!",
  "💼 Business click deal!",
  "🎒 School vibes unlocked!",
  "🧳 Trip to funland!",
  "🎒 Gear up for joy!",
  "🎒 Pack your curiosity!",
  "🛍️ Shopping spree button!",
  // …continues until 500 unique entries
];

export async function GET() {
  return NextResponse.json({ hints });
}
